"""Rebuild the research task catalog and dependency graph; no bot interaction."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'docs/research'
TASKS = []
def task(id, domain, title, status, deps, work, acceptance):
    TASKS.append(dict(id=id,domain=domain,title=title,status=status,depends_on=deps.split(),work=work,acceptance=acceptance))
# Status describes the remaining deliverable, not all pre-existing code in its domain.
task('B01','foundation','Identify the exact running build','partial','', 'Expose backend revision, frontend build, loaded capabilities, game/device identity and active profile; reconcile uncommitted work with the running process.', 'A mismatched frontend/API is visibly blocked from offering unsupported commands; readiness distinguishes watching from playing.')
task('B02','foundation','Version the game concept catalog','partial','B01', 'Extend upgrades.py into namespaced IDs for stats, unlocks, labs, UWs, cards, modules, perks, currencies and later systems; attach aliases, units, caps, prerequisites, authoritative sources and game-version validity.', 'Every glossary entry maps to a concept/domain or an explicit alias/strategy/reference record; unfamiliar OCR text never silently becomes an executable upgrade.')
task('B03','foundation','Persist account and run state separately','missing','B02', 'Create immutable account revisions and separate run observations. Store base Workshop levels, lab levels, effective stats, inventory, unlocks and settings with observation time, confidence, frame evidence and unknown values.', 'A battle-buffed Health value cannot overwrite base Workshop Health; missing levels stay unknown; restart restores the latest verified account revision.')
task('B04','foundation','Discover all supported screens and rows','partial','B02 B03', 'Generalize OCR navigation to menus, nested tabs, scroll lists, popups and account readers; validate screen geometry and locale; distinguish locked, unseen, unavailable, maxed and unreadable.', 'Recorded screens across supported unlock stages resolve stable IDs without fixed row ordering; new tabs do not shift a purchase to a different target.')
task('B05','foundation','Journal and verify every transaction','partial','B03 B04', 'Introduce durable intent, preconditions, one device action, confirmation and reconciliation. Correlate wallet, level/inventory and UI acknowledgement; separate free upgrades and passive income from purchased effects.', 'A crash after a successful tap does not buy twice; a free upgrade does not falsely confirm a cash purchase; card opening is not logged as bought without evidence.')
task('B06','foundation','Recover the device and bot lifecycle','partial','B01 B05', 'Use a single device lease and durable supervisor for ADB reconnect, game resume/relaunch, transient failures, bounded retry/backoff and crash recovery; preserve the verified account identity.', 'Inject disconnect, stale frame and process restart; recover the correct device and pending action or enter an explicit bounded blocked state without uncontrolled tapping.')
task('B07','foundation','Allocate currencies and reserves','partial','B03 B05', 'Separate run cash from permanent coins, gems, stones, medals, cells, keys, shards, tickets, Bits and other versioned resources. Reserve across competing plans and timers, not just per shopping visit.', 'Two queued actions cannot reserve the same funds; lab-slot savings and UW synchronization savings survive lower-priority purchases and process restarts.')
task('B08','foundation','Build representative replay fixtures','partial','B02 B04', 'Extend OCR fixtures with before/after action sequences and account snapshots for each supported subsystem, ambiguous reads, expensive confirmations, overlays and late-game layouts.', 'Each enabled capability has positive, unavailable and ambiguous-state examples plus a reproducible focused verification command; unsupported capabilities remain disabled.')
task('F01','farming','Observe combat and run context','partial','B03 B04', 'Read wave, tier, game speed, elapsed time, health/recovery/wall state, enemy damage and modifiers, perks, cash, UW/card state and run purpose as separate observations.', 'The planner detects a changed run/build and expires cached rows; decision-critical missing HUD values prevent the affected action instead of defaulting to zero.')
task('F02','farming','Complete battle upgrade execution','partial','F01 B05 B07', 'Finish Attack/Defense/Utility traversal, target semantics, buy mode, reserves and maxed rows; make Turtle/Health policy prerequisites explicit and support revisiting affordable priorities.', 'A recorded multi-tab run buys the intended semantic upgrade once, handles free-upgrade interference, respects cash reserve and reaches its configured target.')
task('F03','farming','Complete Workshop progression','partial','B02 B04 B05 B07', 'Model every standard unlock chain and actual levels/costs, purchase batches and decreasing stats. Replace limited early unlock links with verified account prerequisites and stage-aware exclusions.', 'An initially locked upgrade becomes discoverable through its prerequisite chain; no premature Wall/Rend or irrelevant unlock is bought; target spending remains bounded.')
task('F04','farming','Route runs through maintenance','partial','F02 F03 B06', 'Choose retry versus home after death based on due work; arbitrate battle, Workshop, research, rewards and return navigation with a durable maintenance queue.', 'Complete run → game over → home → due maintenance → next run without a manual tap; repeated RETRY cannot starve account upgrades.')
task('F05','farming','Choose tiers and run objectives','partial','F01 F04 F09', 'Execute tier selection/unlocks and farm versus milestone objectives. Compare coins/hour and cells/hour including downtime; explore enough eligible tiers and record confidence/build context.', 'Select and visually confirm the requested tier; do not infer a best tier from Tier 1 alone or mix short milestone attempts with ordinary farming samples.')
task('F06','farming','Choose and configure perks','missing','B04 B05 F01', 'Read offered normal/UW/tradeoff perks, current stacks and perk settings; implement build/purpose-specific picks, bans, priorities and unlocks for automatic perk facilities.', 'Handle a blocking perk choice and resume the run; reject a harmful tradeoff under the active build and record why the chosen perk was preferred.')
task('F07','farming','Manage run loadouts and active skills','missing','F01 C01 C02', 'Select farming, milestone, event and tournament card sets; track swap restrictions and active-card cooldown/usage; coordinate UW and targeting settings when their executors become available.', 'Loadout is confirmed before the run; locked in-run cards are not swapped; active abilities fire at configured conditions and restore the farming preset afterward.')
task('F08','farming','Handle rewards and blocking overlays','missing','B04 B05 B06', 'Classify daily login, gems, reward claims, result screens, known ad flows, disconnect notices and known dismissible popups. Track reward availability, completion and timeout.', 'Known interruptions resume the prior objective with verified rewards; an unrecognized overlay triggers bounded recovery instead of blind clicks or endless scanning.')
task('F09','farming','Measure outcomes with build context','partial','B03 B05 F01', 'Extend run history with verified tier/wave, coins/cells/shards, real elapsed time including visits, death reason, active build and optimizer/account revision; retain missing-data flags.', 'Rates exclude invalid/zero-duration data; two build variants can be compared using reproducible eligible samples rather than counting taps as successful upgrades.')
task('L01','labs','Read labs, slots and research timers','missing','B03 B04', 'Read lab ownership, unlocked research, exact levels/costs/durations, active jobs, queues, speeds and acceleration state; model unlock milestones.', 'All owned lab slots and active completions survive a restart; an unseen lab is not assumed unresearched.')
task('L02','labs','Run continuous research','missing','L01 B05 B07 F04', 'Unlock slots under the gem plan and execute start/queue/repeat/replace research with explicit prerequisites, completion confirmation and policy for interrupted jobs.', 'A lab finishing during a battle is replenished at the next safe opportunity; coins remain reserved and the same research is not started twice.')
task('L03','labs','Schedule lab acceleration','missing','L02 B07 F09', 'Allocate cells to supported speed-up tiers/durations and optional gem rushing under explicit saved limits; model real completion time, queue occupancy and next boost expiry.', 'Boosts stay within projected cell income/reserve, expired boosts are renewed when eligible, and unavailable acceleration is skipped without blocking research.')
task('L04','labs','Balance essential and optimizer research','missing','L02 E04 E05', 'Keep essential progression/QoL research and account prerequisites alongside eHP/eRegen/eDamage/eEcon recommendations; choose independent slot jobs by goal, time and currency constraints.', 'All slots receive eligible work; a high-ranked optional stat lab cannot displace a required unlock or lab-speed policy merely because it appears in a path.')
task('C01','cards_modules','Read cards, slots and mastery','missing','B03 B04', 'Inventory card identities, copies, levels, unlocked/equipped slots, presets, in-run locks and mastery ownership; distinguish passive bonuses from active abilities.', 'Exact equipped cards and available slots are known before calculating effective stats; missing card observations remain explicit.')
task('C02','cards_modules','Verify card purchases and equipment','partial','C01 B05 B07 F04', 'Confirm card pack results and gem deductions, open slots, equip/save presets and enforce the lab-slot-first resource plan; integrate event card-purchase goals.', 'A purchased pack reconciles copies and gems; a lab-slot reserve is preserved; each preset is read back after applying it.')
task('C03','cards_modules','Read primary and assist modules','missing','B03 B04', 'Inventory Cannon/Armor/Generator/Core and assist modules, equipped slots, levels, rarity, stars, unique effects, subeffects, shards and restrictions.', 'Account state distinguishes unique-effect rarity scaling, main stats and primary/assist effects; every equipped module resolves to the correct category.')
task('C04','cards_modules','Upgrade, merge and recycle modules','missing','C03 B05 B07 F04', 'Implement level-up, restoration, merge/unmerge, shatter and acquisition policies with protected copies, rarity prerequisites and shard accounting.', 'A proposed merge preserves required/protected inventory; post-action rarity and resource deltas reconcile; uncertain actions are not repeated.')
task('C05','cards_modules','Optimize module loadouts and subeffects','missing','C03 C04 B07 E05', 'Rank equip/assist combinations per build, reroll with desired effects and locked slots, enforce shard budgets and exact stop conditions; preserve existing useful subeffects.', 'Reroll stops on desired outcomes or budget exhaustion; replacing a module invalidates affected optimizer inputs before another recommendation executes.')
task('C06','cards_modules','Plan card mastery investments','missing','C01 C02 L02 E05 U02', 'Model mastery unlock conditions, stone unlocks, coin/lab follow-ups and active/persistent effects; compare expensive mastery paths with competing UWs and research.', 'A mastery plan checks its full unlock and follow-up costs, updates effective stats, and never spends the stone reserve twice.')
task('E01','effective_paths','Pin the native workbook contract','partial','B02', 'Version Effective Paths, IDS worksheets, actual input/output ranges, currencies, path families and formula dependencies; identify stale guide references and unsupported paths.', 'A known workbook revision produces a machine-readable contract; a changed or unknown workbook layout is detected before any recommendation can execute.')
task('E02','effective_paths','Populate calculator inputs from account state','missing','E01 B03 L01 C01 C03 U01 F09', 'Map readers to IDS and direct EP inputs, preserving base levels versus run-max levels, raw UWs versus lab/subeffect modifiers, loadout, perks, modules, economy outcomes and estimated assumptions. Add Guardian/Vault/Dissonance inputs as those readers become available; each path declares its required capabilities.', 'Every required field has provenance or an explicit assumption; public template/example values cannot be mistaken for this account; stale critical fields block only dependent paths.')
task('E03','effective_paths','Recalculate a versioned personal model','missing','E01 E02', 'Implement a connector to an authorized personal workbook or a compatible validated local calculation engine. Detect formula errors, external IDS dependencies, calculation completion and output freshness.', 'A calculation result names both workbook and account revision, matches golden cases, and is rejected if inputs changed or dependent formulas are still stale.')
task('E04','effective_paths','Normalize all native recommendation types','partial','E03 B02', 'Extend the manual advisor import to native eHP/eRegen/eDamage/eEcon variants, coin/stone/key and discount outputs with levels, units, gain, cost, duration, uncertainty and executor capability.', 'Each result is executable, blocked for a named prerequisite, or advisory with a reason; standard Workshop planning is not falsely presented as a native EP path.')
task('E05','effective_paths','Choose goals and resolve prerequisites','missing','E04 B07', 'Allocate a portfolio across incomparable health, damage, regen and economy goals using saved preferences and build constraints; schedule prerequisite chains and savings; retain essential non-EP priorities.', 'The selected next action is explained with opportunity cost and dependencies; goals in different units are not ranked by a raw benefit number; hard exclusions override optional rankings.')
task('E06','effective_paths','Check proposals before execution','missing','E05 B05 B08', 'Run feasibility and affordability checks, simulate the planned stat/resource change, assert sync and build invariants, and compare against workbook fixture outputs in shadow mode.', 'Invalid levels, wrong units, unaffordable bundles, stale evidence and broken synchronization are rejected in replay without affecting the device.')
task('E07','effective_paths','Close the observe–optimize–act loop','missing','E06 F04 L04', 'Promote eligible plans under saved authority, dispatch to available domain executors, verify the change, refresh inputs and replan; continue safe farming when an optional path is unsupported.', 'One supported native recommendation completes from account observation through confirmed in-game change and a new calculation without import, stage or Save clicks.')
task('U01','ultimate_weapons','Read Ultimate Weapons and UW+','missing','B03 B04', 'Read owned UWs, offered unlock choices, raw levels/values/costs, labs, toggles, cooldowns/durations, plus-system state and account prerequisites.', 'All nine base UW identities and current observed ownership are represented; lab/subeffect-adjusted values never masquerade as raw stone upgrades.')
task('U02','ultimate_weapons','Choose and buy stone upgrades','missing','U01 B05 B07 E05', 'Evaluate offered UWs and stone-level paths against the account build, save-up goals and prerequisite bundles; perform verified selection and upgrade actions.', 'A stone action preserves reserves and intended synchronization and confirms the actual weapon/level; unavailable offers trigger replanning.')
task('U03','ultimate_weapons','Maintain UW and bot synchronization','missing','U01 U02 F01', 'Model base cooldowns, durations, overlap, partial versus full sync, UW timing toggles and module/perk modifiers; preserve account-specific GT/BH/DW/Golden Bot constraints.', 'A proposed cooldown change cannot silently break a protected overlap; actual observed cycles and model assumptions are reported separately.')
task('U04','ultimate_weapons','Execute UW+ and advanced combinations','missing','U02 U03 L02 C05', 'Add plus unlocks, advanced UW labs and activation policies for late-game damage/economy builds using version-specific formulas and observation.', 'All enabled UW+ upgrades have prerequisites, cost and verified postconditions; advanced build presets apply consistently across labs/modules/perks.')
task('U05','ultimate_weapons','Manage event bots and Bot+','missing','B03 B04 B05 B07 U03 T02', 'Model each current event bot, unlock/medal levels, cooldown/range/duration/bonus, labs and toggles; cover Bot Bot and Bot+ when eligible.', 'A bot upgrade reconciles medals and levels while preserving protected sync and event purchases; a glossary count cannot hide a current bot.')
task('A01','advanced','Buy Workshop Enhancements','missing','F03 B07 E05', 'Read enhancement unlocks, levels, coin costs and category progression; execute EP enhancement recommendations independently of ordinary Workshop stats.', 'An enhancement purchase updates the matching calculator multiplier once and confirms any newly unlocked enhancement options.')
task('A02','advanced','Unlock and develop the Wall deliberately','partial','F03 L04 A01 E05', 'Treat existing Wall stat catalog entries as only a starting point; add readiness thresholds, Wall lab commitments, regen/fortification/thorns and health interactions.', 'Wall is unlocked only after the configured full readiness predicate; required research and budget follow through instead of leaving a harmful half-built state.')
task('A03','advanced','Manage build transitions and respecs','missing','F02 F03 F06 F07 C05 U03 E05', 'Model Turtle, Blender/eHP, hybrid, Devo/orb-devo/orbless and glass-cannon eligibility with account-specific goals; plan reversible loadout changes and controlled Workshop respecs.', 'A chosen transition has a verified precondition checklist and ordered restore plan; free-upgrade, range and sync settings match the intended build before farming resumes.')
task('A04','advanced','Control targeting, range and positioning','missing','B04 B05 F01 F06 A03', 'Execute target priority, orb adjustments, range/shockwave sliders, UW toggles and other supported in-run controls; account for enemies, elites and battle conditions.', 'Controls are applied and read back for the current mode; locked or unsupported controls are skipped with an explicit capability reason.')
task('A05','advanced','Manage Vault trees and keys','missing','B03 B04 B05 B07 E05 T03', 'Read the current tree catalog, unlock prerequisites and key economy; implement tree purchases/respec policy and integrate the native EP key path where supported.', 'A tree node purchase confirms prerequisite, key cost and resulting bonus; old two-tree documentation cannot truncate the current catalog.')
task('A06','advanced','Manage Guardian chips and materials','missing','B03 B04 B05 B07 E05', 'Read Guardian unlocks and current chip catalog including Scout, levels, cooldowns, materials and effects; support IDS input mapping, purchases and run usage.', 'An eligible chip action reconciles materials and updates affected economy/combat inputs; unobserved chips remain unknown rather than absent.')
task('T01','recurring','Complete daily and weekly objectives','missing','B03 B04 B05 F04 F08', 'Read reset timers, objective progress and reward tracks; claim free rewards and schedule compatible actions with deduplication and missed-reset handling.', 'Across a reset, completed rewards are claimed once and unfinished goals are carried or expired correctly without interrupting a more valuable run unnecessarily.')
task('T02','recurring','Plan events and event-shop spending','missing','T01 B07 E05', 'Read timed missions, event progress, shop inventory and prices; choose attainable goals and medal purchases, accounting for relic/theme priorities and rising purchase costs.', 'Reserve event currency for the selected targets, execute compatible mission runs, claim milestones and stop at the configured completion/budget limit.')
task('T03','recurring','Participate in tournaments','missing','F05 F07 F09 T01 E05', 'Read tournament schedule/league/tickets/rewards and battle conditions; choose a competitive loadout and time window, enter, run, claim, and restore farming.', 'One tournament cycle respects tickets, applies the correct conditions, records result and returns to farming; tournament runs do not distort farming comparisons.')
task('T04','recurring','Track milestones, relics and cosmetics','missing','F05 T01 T02 B03 B05', 'Read and claim tier milestones and unlocks; inventory relics, skins/backgrounds/songs and effective bonuses; model eligible free/owned pass rewards separately.', 'Claimed rewards and passive bonuses reconcile once; future model calculations include owned bonuses even when a cosmetic is not equipped.')
task('T05','recurring','Support guild and seasonal systems','missing','T01 T02 F07 B07', 'Version guild objectives, co-op/dungeon activities, seasonal modifiers, tokens and Bits; add readers, attainable-goal policy and actions for the supported account/version.', 'A supported activity has known schedule, resource and reward semantics; social/account setup dependencies are recorded and do not block ordinary solo farming.')
task('T06','recurring','Automate Dissonance and Echo progression','missing','A03 A04 U04 A05 A06 T04', 'Read Dissonance unlocks/run constraints, Echo and build-specific requirements; plan specialized attempts, respec/loadout restoration and permanent reward effects.', 'Complete a supported Dissonant objective with verified setup, reward and return to farming; no late-game mode is marked supported from its name alone.')
task('O01','operations','Show a complete account inspector','partial','B03', 'Replace dated account literals with observed account inventory, field freshness, source frame, unlock dependencies, supported capability and missing-input views.', 'The user can trace every optimizer-critical value to an observation or declared estimate and distinguish unavailable from not yet scanned.')
task('O02','operations','Configure goals and standing authority','partial','B07 E05', 'Provide saved farming/progression priorities, reserves, forbidden upgrades, sync constraints, allowed currencies and mode schedules; make no-routine-approval mode explicit.', 'A saved policy authorizes supported routine actions without repeated confirmations while unsupported/forbidden actions cannot be armed accidentally.')
task('O03','operations','Explain each plan and purchase','partial','E06 B05', 'Extend live decisions into a dependency view: current goal, next action, alternatives, blockers, cost, source version and expected/observed result.', 'A displayed decision can be replayed from its account/policy/workbook revisions, including why a cheaper-looking alternative was not chosen.')
task('O04','operations','Expose schedules and progression results','partial','F09 L03 T01', 'Show research queue, currency commitments, event/tournament deadlines, next maintenance visit, progression metrics and goal completion; keep automation schedule independent of the dashboard tab.', 'Closing the browser does not stop scheduling; measured results link to the exact build and decision history.')
task('O05','operations','Provide incident and recovery controls','partial','B06 F08 O03', 'Show recovery attempts, current blocking evidence, degraded capabilities and safe resume/stop controls; retain machine-readable incident bundles.', 'A stuck optional subsystem can be quarantined while safe core farming continues; unresolved global state stops spending and gives one actionable incident.')
task('V01','validation','Prove subsystem coverage in replay','partial','B08 B05', 'Maintain a scenario matrix per enabled reader/executor, covering unlocks, max levels, missing inputs, currencies, ambiguous outcomes and version changes.', 'All enabled actions pass their relevant focused fixture/API checks; catalogs, schemas and unexecuted tests do not count as live support.')
task('V02','validation','Prove calculator and decision parity','missing','E06 V01', 'Run representative account fixtures through native EP and the connector; verify ranges, units, output order and tolerances; shadow proposed decisions against actual account observations.', 'Every enabled native path has version-pinned golden cases; any mismatch disables affected execution until resolved.')
task('V03','validation','Prove recovery under faults','missing','B06 F04 F08 V01', 'Inject process loss before/after taps, ADB loss, unknown overlays, missing UI replies, stale calculator output, full queues and resource races.', 'Every scenario reaches an explicit recover/skip/blocked outcome within its configured bound; no duplicate spending or silent data corruption occurs.')
task('V04','validation','Certify overnight farming','missing','F04 F05 F06 F07 F08 L02 C02 V03 O05', 'Run a controlled 24-hour acceptance session with available early-game systems, a fixed policy and recorded baseline; inspect intervention and action outcomes.', 'Zero routine manual taps; every purchase reconciled; no indefinitely blocked known screen; all due supported maintenance serviced; resource reserves preserved.')
task('V05','validation','Certify optimizer-led weekly operation','missing','E07 L03 C05 C06 U04 U05 A01 A02 A03 A04 A05 A06 T01 T02 T03 T04 T05 T06 O02 O04 V02 V04', 'Qualify supported late-game/account capabilities incrementally, then run a seven-day soak spanning resets, research turnover and available scheduled activities.', 'Zero routine intervention across the enabled scope; all covered recommendation types execute and recalculate correctly; unavailable game modes have explicit coverage exclusions.')
task('V06','validation','Maintain version compatibility','missing','B01 B02 E01 V01 O05', 'Detect game, wiki, glossary and workbook changes; diff concepts and fixtures; quarantine incompatible paths and roll out updated adapters after focused qualification.', 'A changed label, new system or workbook schema cannot silently reroute spending; unaffected verified farming continues when safe.')
DOMAINS={
'foundation':dict(name='Account truth and execution',phase=0,files=['upgrades.py','perception.py','autopilot.py','device.py','runner.py','events.py','ledger.py','web/app.py'],proposed=['account.py','transactions.py','supervisor.py','currencies.py'],source='https://www.tower-hub.com/glossary'),
'farming':dict(name='Reliable farming loop',phase=1,files=['tower_bot.py','autopilot.py','policy.py','shopping.py','navigate.py','progression.py','runs.py'],proposed=['maintenance.py','perks.py','run_loadouts.py'],source='https://www.tower-hub.com/wiki/guide'),
'labs':dict(name='Labs and acceleration',phase=2,files=['shopping.py','strategy.py','ledger.py'],proposed=['labs.py','research_policy.py'],source='https://www.tower-hub.com/wiki/lab/laboratory'),
'cards_modules':dict(name='Cards and modules',phase=2,files=['shopping.py','strategy.py'],proposed=['cards.py','modules.py','loadouts.py'],source='https://www.tower-hub.com/wiki/module'),
'effective_paths':dict(name='Effective Paths loop',phase=3,files=['advisor.py','web/advisor.py','web/ui/components/AdvisorPanel.tsx'],proposed=['effective_paths/contract.py','effective_paths/inputs.py','effective_paths/connector.py','planner.py'],source='https://the-tower.notion.site/Effective-Paths-1bb91383b93f80d5aed2c098cbbd9e46'),
'ultimate_weapons':dict(name='Ultimate Weapons and event bots',phase=4,files=['policy.py','strategy.py'],proposed=['ultimate_weapons.py','synchronization.py','event_bots.py'],source='https://www.tower-hub.com/wiki/uw'),
'advanced':dict(name='Advanced builds and systems',phase=4,files=['upgrades.py','policy.py','strategy.py'],proposed=['enhancements.py','builds.py','vault.py','guardian.py'],source='https://www.tower-hub.com/wiki/system'),
'recurring':dict(name='Events and long-term progression',phase=5,files=['pages.py','runs.py','progression.py'],proposed=['missions.py','tournaments.py','rewards.py','guilds.py','dissonance.py'],source='https://www.tower-hub.com/wiki/system'),
'operations':dict(name='Control room',phase=6,files=['web/app.py','web/ui/components/Sidebar.tsx','web/ui/app/strategy/page.tsx','web/ui/components/AutopilotStatus.tsx'],proposed=['web/ui/app/account/page.tsx','web/ui/app/progression/page.tsx'],source=None),
'validation':dict(name='Unattended qualification',phase=6,files=['tests/test_autopilot.py','tests/test_shopping_autopilot.py','tests/test_advisor.py','tests/test_runner.py'],proposed=['tests/fixtures/account/','tests/fixtures/effective_paths/','tests/test_recovery.py'],source=None),
}
ids={t['id'] for t in TASKS}; assert len(ids)==len(TASKS)
for t in TASKS: assert set(t['depends_on'])<=ids,(t['id'],t['depends_on'])
visited=set(); active=set()
def visit(id):
    assert id not in active, ('cycle',id)
    if id in visited:return
    active.add(id)
    for dep in next(t for t in TASKS if t['id']==id)['depends_on']:visit(dep)
    active.remove(id);visited.add(id)
for id in ids:visit(id)
doc=dict(audit_date='2026-09-05',note='Proposed remaining deliverables. Partial means reusable code exists; no task below is certified complete. Dependencies are engineering prerequisites, not a schedule.',domains=DOMAINS,tasks=TASKS)
(OUT/'2026-09-05-autonomy-tasks.json').write_text(json.dumps(doc,indent=2)+'\n')
lines=['flowchart LR']
for domain,d in DOMAINS.items():
    lines.append(f'  subgraph {domain}["{d["name"]}"]')
    for t in TASKS:
        if t['domain']==domain: lines.append(f'    {t["id"]}["{t["id"]} · {t["title"]}"]')
    lines.append('  end')
for t in TASKS:
    for dep in t['depends_on']:lines.append(f'  {dep} --> {t["id"]}')
lines += ['  classDef partial fill:#fff3d6,stroke:#946200,color:#262626','  classDef missing fill:#f2f4f7,stroke:#73808c,color:#262626']
for status in ('partial','missing'):lines.append('  class '+','.join(t['id'] for t in TASKS if t['status']==status)+' '+status)
(OUT/'2026-09-05-autonomy-dependencies.mmd').write_text('\n'.join(lines)+'\n')
parts=['# Remaining automation task catalog','',doc['note'],'']
for domain,d in DOMAINS.items():
    parts += ['## '+d['name'],'','Existing integration points: '+', '.join('`'+f+'`' for f in d['files'])+'.','', 'Proposed focused modules: '+', '.join('`'+f+'`' for f in d['proposed'])+'. These are suggested boundaries, not implemented files.','']
    if d['source']:parts+=['Game reference: [source]('+d['source']+').','']
    for t in TASKS:
        if t['domain']!=domain:continue
        parts += [f'### {t["id"]} — {t["title"]}','',f'- [ ] **{t["status"].capitalize()}** — dependencies: '+(', '.join(t['depends_on']) or 'none')+'.','',t['work'],'','**Acceptance:** '+t['acceptance'],'']
(OUT/'2026-09-05-autonomy-task-catalog.md').write_text('\n'.join(parts))
print(json.dumps({'tasks':len(TASKS),'partial':sum(t['status']=='partial' for t in TASKS),'missing':sum(t['status']=='missing' for t in TASKS),'dependency_edges':sum(len(t['depends_on']) for t in TASKS),'dag_valid':True,'domains':len(DOMAINS)}))
